# -*- coding: utf-8 -*-
"""calculadora.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JdWdkMxcwK40NdFydg_tNN8JHmYL4huB
"""

print('Bem vindo à sua calculadora!!!') # Mensagem de boas vindas

calculate() #chamar a função calculate()

def calculate():
  num1 = int(input('Digite seu primeiro número: '))
  num2 = int(input('Digite seu segundo número: '))

#soma
print ('{} + {} = '.format(num1, num2))
print (num1 + num2)

#subtração
print ('{} - {} =' .format(num1, num2))
print (num1 - num2)

#multiplicação
print ('{} * {} =' .format(num1, num2))
print (num1 * num2)

#divisão
print ('{} / {} =' .format(num1, num2))
print (num1 / num2)

operacao = input ('''
Por favor digite a operação que deseja realizar:
+ adição
- subtração
* multipplicação
/ divisão
''')

if operacao == '+':
   print ('{} + {} = '.format(num1, num2))
   print (num1 + num2)

elif operacao == '-':
   print ('{} - {} = '.format(num1, num2))
   print (num1 - num2)

elif operacao == '*':
   print ('{} * {} = '.format(num1, num2))
   print (num1 * num2)

elif operacao == '/':
   print ('{} / {} = '.format(num1, num2))
   print (num1 / num2)


else:
   print ('Operação inválida')

again() #chamar a função again() após o cálculo.

def again():
  calc_again = input('''
Gostaria de fazer mais alguma operação?
Digite 'S' para sim ou 'N' para não.
''')

  if calc_again.upper() == 'S':
       calculate()
  elif calc_again.upper() == 'N':
       print('Até mais parceiro!')
  else:
       again()

calculate()